### ISSUE TITLE
怎么使用这个客户端呢？

### ISSUE THREAD

**Issue by kechujian** [multilinguals/apollo-php-client#11]
php start.php 提示
"status":404,"error":"Not Found","message":"No message available","path":"/notifications/v2"}

**Comment by Sidfate** [comment]
@kechujian 这个报错提示你设置的apollo的服务地址`CONFIG_SERVER`可能不正确，请检查下你是否设置了`CONFIG_SERVER`全局变量；如果设置了，检查下这个地址是否可用。

**Comment by kechujian** [comment]
设置了的http://xxx.xxx.xxx.xxx:8090
![image](https://user-images.githubusercontent.com/18072353/46851308-aa3e7100-ce29-11e8-8865-3e7897460d79.png)
怎么测试呢？apollo服务端需要用到8090这个端口吗？服务端是正常的。

**Comment by Sidfate** [comment]
你可以试下你设置的`http://xxx.xxx.xxx.xxx:8090`地址，根据[apollo自身接口文档](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#121-http%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E)里的接口调用是否可以拉取配置。很可能是`http://xxx.xxx.xxx.xxx:8090`的服务没有正常起来，导致接口返回了404.

**Comment by kechujian** [comment]
http://xxx.xxx.xxx.xxx:8090 在浏览器打开显示 apollo-adminservice，这样应该是通的吧

**Comment by kechujian** [comment]
> 你可以试下你设置的`http://xxx.xxx.xxx.xxx:8090`地址，根据[apollo自身接口文档](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#121-http%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E)里的接口调用是否可以拉取配置。很可能是`http://xxx.xxx.xxx.xxx:8090`的服务没有正常起来，导致接口返回了404.

http://xxx.xxx.xxx.xxx:8090 在浏览器打开显示 apollo-adminservice，这样应该是通的吧

**Comment by kechujian** [comment]
试出来了，应该用8080端口

**Comment by kechujian** [comment]
在实际应用的时候，应该是跑一个cli，一直去读取配置，修改配置文件吗？

**Comment by Sidfate** [comment]
@kechujian 你只要执行以下命令

```shell
$ php start.php
```
已经跑起来，然后你想让进程常驻，可以使用操作系统的自带的方法，这个就不同处理了，例如linux可以：

```shell
$ php start.php &
```
