### ISSUE TITLE
请求notifications/v2? 接口卡住

### ISSUE THREAD

**Issue by yunnian** [multilinguals/apollo-php-client#15]
_listenChange 无响应 跟了下代码在 curl_exec 就卡住了 ，没有响应 最后超时
120.55.38.192:8080/notifications/v2?appId=2&cluster=default&notifications=%5B%7B%22namespaceName%22%3A%22env%22%2C%22notificationId%22%3A-1%7D%5D

**Comment by xiaodx12** [comment]
这个地址你能ping通或端口能telnet通吗

**Comment by yunnian** [comment]
可以通的 我去掉namespace参数 还会报参数错误什么的，代码恢复就不通了

**Comment by xiaodx12** [comment]
加我微信吧，xiao_dx_12
